Creating pipeline (#9)
* Creating pipeline

* Changing flow

* Adding heroku api key

* Change tag

* Adding secrets

* Changing env

* Changing secrets

* Changing heroku token

* Changing github token

* Changing tests

* Fixing pipeline

* Changing script

* Adding comments

* Changing build way

* Adding echo platforms

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,10 +4,48 @@ on:
   push:
     branches:
       - master
+  pull_request:
+    types: [opened, reopened, synchronize, labeled, closed]
+  pull_request_target:
+    types: [opened, reopened, synchronize, labeled, closed]
 
 jobs:
+  build-test:
+    name: tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2 # checkout the repo
+      - run: npm ci # install packages
+      - run: npm test # run tests (configured to use jest-junit reporter)
+
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure() # run this step even if previous step failed
+      #   with:
+      #     name: JEST Tests # Name of the check run which will be created
+      #     path: reports/jest-*.xml # Path to test results
+      #     reporter: jest-junit # Format of test results
+
   build:
     runs-on: ubuntu-latest
+    needs: build-test
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v1
+      - name: Inspect builder
+        run: |
+          echo "Name:      ${{ steps.buildx.outputs.name }}"
+          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
+          echo "Status:    ${{ steps.buildx.outputs.status }}"
+          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
+          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
     steps:
       - uses: actions/checkout@v2
       - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
